In [4]:
import numpy as np

A = np.array([
    [0, 1],
    [2, 3],
    [5, 6],
])

B = np.array([
    [0,1,2,3,],
    [4,5,6,7,]
])


C = np.dot(A, B)


print("行列の積の結果:")
print(C)


max_value = np.max(C)

print("最大値:", max_value)

行列の積の結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [24 35 46 57]]
最大値: 57
